steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/serious-hall-371508/vertex-ai-repo/chatbot:tag1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/serious-hall-371508/vertex-ai-repo/chatbot:tag1']
images:
- 'gcr.io/cloud-builders/docker'

